[package]
name = "tex-druid"
version = "0.1.0"
authors = ["Alanna Kelly <alanna@alannakelly.ie>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.16.8"
structview = "1.1.0"
rgb = "0.8.25"